/*
 * Don't Die Game
 * CS 321 - 01
 * Team 4: Hunter Bales, Harleigh Bass, Anushka Bhattacharjee, Liam Coddington
 * FALL SEMESTER - 2 December 2019
 */
package GUI;

import Model.*;
import dontdie.audio.AudioController;
import java.awt.Color;
import java.awt.Font;
import organism.Player;

/**
 * GameOver.java JFrame that shows the Game Over screen, the number of points
 * you won through playing the game, and the ability to exit the game and go
 * back to the Main Menu.
 * Javadocs checked by Anushka Bhattacharjee
 * @author Hunter Bales, Harleigh Bass, and Liam Coddington
 */
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        setLocationRelativeTo(null);
        AudioController audio = new AudioController();
        audio.playGameOverSoundtrack();

        GameLoop loop = GameLoop.getInstance();
        
        Player player = new Player();
        if (player.isPlayerAlive()) {
            gameResults.setText("\n\nCongrats, you have survived!! Great Job!!");
        } else {
            gameResults.setText("\n\nYou died, you couldn't even survive 3 days.");
        }

        PointSystem pointSystem = PointSystem.getInstance(player, loop);
        pointSystem.setScore();
        String score = "" + pointSystem.getScore();
        scoreTextField.setText(score);

        // Button Colors and Fonts
        MainMenu.setForeground(Color.WHITE);
        ExitGame.setForeground(Color.WHITE);
        GameOver.setForeground(Color.WHITE);
        ScoreResults.setForeground(Color.WHITE);

        MainMenu.setFont(new Font("Arial Black", Font.PLAIN, 14));
        ExitGame.setFont(new Font("Arial Black", Font.PLAIN, 14));
        GameOver.setFont(new Font("Showcase Gothic", Font.BOLD, 36));
        ScoreResults.setFont(new Font("Arial Black", Font.PLAIN, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GameOver = new javax.swing.JLabel();
        MainMenu = new javax.swing.JButton();
        ScoreResults = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameResults = new javax.swing.JTextArea();
        scoreTextField = new javax.swing.JTextField();
        ExitGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        GameOver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GameOver.setText("Game Over");

        MainMenu.setBackground(new java.awt.Color(0, 153, 153));
        MainMenu.setText("Main Menu");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });

        ScoreResults.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ScoreResults.setText("Score:");

        gameResults.setEditable(false);
        gameResults.setBackground(new java.awt.Color(240, 240, 240));
        gameResults.setColumns(20);
        gameResults.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        gameResults.setRows(5);
        gameResults.setText("Congrats, you have survived!! Great Job!!\n\nOR\n\nYou died, you couldn't even survive 3 days.");
        jScrollPane1.setViewportView(gameResults);

        scoreTextField.setEditable(false);
        scoreTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scoreTextField.setText("Your final score");
        scoreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreTextFieldActionPerformed(evt);
            }
        });

        ExitGame.setBackground(new java.awt.Color(255, 102, 102));
        ExitGame.setText("Exit Game");
        ExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GameOver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MainMenu)
                        .addGap(77, 77, 77)
                        .addComponent(ExitGame))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ScoreResults, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameOver, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreResults)
                    .addComponent(scoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainMenu)
                    .addComponent(ExitGame))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * does nothing (couldn't remove)
     * @param evt 
     */
    private void scoreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreTextFieldActionPerformed

    /**
     * returns user to start menu for a new game
     * @param evt 
     */
    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        GameLoop loop = GameLoop.getInstance();
        Player player = new Player();
        PointSystem pointSystem = PointSystem.getInstance(player, loop);
        loop.newGame();
        pointSystem.newGame(loop);
        StartMenu startMenu = new StartMenu();
        startMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuActionPerformed

    /**
     * Exits program.
     * @param evt 
     */
    private void ExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitGame;
    private javax.swing.JLabel GameOver;
    private javax.swing.JButton MainMenu;
    private javax.swing.JLabel ScoreResults;
    private javax.swing.JTextArea gameResults;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scoreTextField;
    // End of variables declaration//GEN-END:variables
}
