/*
 * Don't Die Game
 * CS 321 - 01
 * Team 4: Hunter Bales, Harleigh Bass, Anushka Bhattacharjee, Liam Coddington
 * FALL SEMESTER - 2 December 2019
 */
package GUI;

import dontdie.audio.AudioController;
import java.awt.Color;
import java.awt.Font;

/**
 * StartMenu has buttons to start game, go to OptionsMenu for music volume,
 * go to the AboutMenu, and exit the program.
 * Javadocs checked by Anushka Bhattacharjee
 * @author Hunter Bales and Harleigh Bass
 */
public class StartMenu extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu
     */
    public StartMenu() {
        setSize(740, 560);
        setLocationRelativeTo(null);
        setUndecorated(true);
        
        initComponents();
        
        // Set Button and JLabel text Colors
        DontDieTitleLabel.setForeground(Color.WHITE);
        StartButton.setForeground(Color.WHITE);
        OptionButton.setForeground(Color.WHITE);
        AboutButton.setForeground(Color.WHITE);
        ExitGameButton.setForeground(Color.WHITE);
        
        // Set Button and JLabel text Font
        DontDieTitleLabel.setFont(new Font("Showcard Gothic", Font.BOLD, 48));
        StartButton.setFont(new Font("Arial Black", Font.PLAIN, 16));
        OptionButton.setFont(new Font("Arial Black", Font.PLAIN, 16));
        AboutButton.setFont(new Font("Arial Black", Font.PLAIN, 16));
        ExitGameButton.setFont(new Font("Arial Black", Font.PLAIN, 16));
        
        AudioController audio = new AudioController();
        audio.playMenuSoundtrack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuPanel = new javax.swing.JPanel();
        DontDieTitleLabel = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        OptionButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        ExitGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        MainMenuPanel.setBackground(new java.awt.Color(40, 54, 60));
        MainMenuPanel.setPreferredSize(new java.awt.Dimension(407, 374));

        DontDieTitleLabel.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        DontDieTitleLabel.setText("Don't Die!!");

        StartButton.setBackground(new java.awt.Color(0, 153, 153));
        StartButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        OptionButton.setBackground(new java.awt.Color(0, 153, 153));
        OptionButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OptionButton.setText("Options");
        OptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionButtonActionPerformed(evt);
            }
        });

        AboutButton.setBackground(new java.awt.Color(0, 153, 153));
        AboutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        ExitGameButton.setBackground(new java.awt.Color(255, 102, 102));
        ExitGameButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitGameButton.setText("Exit Game");
        ExitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuPanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ExitGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OptionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainMenuPanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(DontDieTitleLabel)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(DontDieTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(OptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ExitGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens a small OptionsMenu to adjust volume from the screen.
     * @param evt from being clicked on.
     */
    private void OptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionButtonActionPerformed

        OptionsMenu options = new OptionsMenu();
        options.setVisible(true);
        
    }//GEN-LAST:event_OptionButtonActionPerformed

    /**
     * Closes the MainMenu to load a GameScene in order to play the game.
     * @param evt from being clicked on.
     */
    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        GameScene gamescene = new GameScene();
        gamescene.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_StartButtonActionPerformed

    /**
     * Closes the program.
     * @param evt from being clicked on.
     */
    private void ExitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitGameButtonActionPerformed

    /**
     * Closes the MainMenu to load an AboutMenu to show the Creators, the class
     * this was made for, and how to play the game.
     * @param evt from being clicked on.
     */
    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
       AboutMenu aboutMenu = new AboutMenu();
       aboutMenu.setVisible(true);
    }//GEN-LAST:event_AboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

                start = new StartMenu();
                start.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JLabel DontDieTitleLabel;
    private javax.swing.JButton ExitGameButton;
    private javax.swing.JPanel MainMenuPanel;
    private javax.swing.JButton OptionButton;
    private javax.swing.JButton StartButton;
    // End of variables declaration//GEN-END:variables
    private static StartMenu start;
}
