/*
 * Don't Die Game
 * CS 321 - 01
 * Team 4: Hunter Bales, Harleigh Bass, Anushka Bhattacharjee, Liam Coddington
 * FALL SEMESTER - 2 December 2019
 */
package GUI;

import java.awt.Color;
import organism.Player;
import organism.StatsEvent;
import organism.StatsListener;

/**
 * StatBarPanel has the layout for the health, hunger, thirst,
 * and energy percentages for the player.
 * Javadocs checked by Anushka Bhattacharjee
 * @author Harleigh Bass (JPanel Design) and Liam Coddington (code)
 */
public class StatBarPanel extends javax.swing.JPanel implements StatsListener {

    private int healthPercent;
    private int hungerPercent;
    private int thirstPercent;
    private int energyPercent;
    
    /**
     * Keeps the status bars updated in the GameScene.
     * @param event Instance of StatsEvent
     */
    public void updatedStats(StatsEvent event)
    {
        healthPercent = event.getHealth();
        healthBar.setValue(healthPercent);
        healthBar.setString(healthPercent + "%");
        hungerPercent = event.getHunger();
        hungerBar.setValue(hungerPercent);
        hungerBar.setString(hungerPercent + "%");
        thirstPercent = event.getThirst();
        thirstBar.setValue(thirstPercent);
        thirstBar.setString(thirstPercent + "%");
        energyPercent = event.getEnergy();
        energyBar.setValue(energyPercent);
        energyBar.setString(energyPercent + "%");
    }
    
    /**
     * Creates new form StatBarPanel.
     * by Harleigh Bass
     */
    public StatBarPanel() {
        initComponents();
        Player player = new Player();
        player.addStatsListener(this);
        
        healthPercent = 100;
        hungerPercent = 100;
        thirstPercent = 100;
        energyPercent = 100;
        
        // Colors of Health Bar
        healthBar.setStringPainted(true);
        healthBar.setForeground(Color.green);
        healthBar.setBackground(Color.gray);
        healthBar.setValue(healthPercent);
        healthBar.setString(healthPercent + "%");
        
        // Colors of Hunger Bar
        hungerBar.setStringPainted(true);
        hungerBar.setForeground(Color.orange);
        hungerBar.setBackground(Color.gray);
        hungerBar.setValue(hungerPercent);
        hungerBar.setString(hungerPercent + "%");
        
        // Colors of Thirst Bar
        thirstBar.setStringPainted(true);
        thirstBar.setForeground(Color.CYAN);
        thirstBar.setBackground(Color.gray);
        thirstBar.setValue(thirstPercent);
        thirstBar.setString(thirstPercent + "%");
        
        // Colors of Energy Bar
        energyBar.setStringPainted(true);
        energyBar.setForeground(Color.BLUE);
        energyBar.setBackground(Color.gray);
        energyBar.setValue(energyPercent);
        energyBar.setString(energyPercent + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        healthLabel = new javax.swing.JLabel();
        healthBar = new javax.swing.JProgressBar();
        hungerLabel = new javax.swing.JLabel();
        hungerBar = new javax.swing.JProgressBar();
        thirstLabel = new javax.swing.JLabel();
        thirstBar = new javax.swing.JProgressBar();
        energyLabel = new javax.swing.JLabel();
        energyBar = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(350, 106));

        healthLabel.setText("Health");

        hungerLabel.setText("Hunger");

        thirstLabel.setText("Thirst");

        energyLabel.setText("Energy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(healthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(thirstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hungerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(energyLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hungerBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thirstBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(healthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hungerLabel)
                    .addComponent(hungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thirstLabel)
                    .addComponent(thirstBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(energyLabel)
                    .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar energyBar;
    private javax.swing.JLabel energyLabel;
    public static javax.swing.JProgressBar healthBar;
    private javax.swing.JLabel healthLabel;
    public static javax.swing.JProgressBar hungerBar;
    private javax.swing.JLabel hungerLabel;
    public static javax.swing.JProgressBar thirstBar;
    private javax.swing.JLabel thirstLabel;
    // End of variables declaration//GEN-END:variables
}
